# -*- coding: utf-8 -*-
"""Pregnancy Drug Safety.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J9w7Wumx-m_sbC47U4aocQUMdpvNwLaO
"""

import streamlit as st
import pandas as pd
import joblib
import numpy as np
from scipy.sparse import hstack
import os
from PIL import Image
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

os.chdir(r"C:\Users\pvspa\Downloads\Pregnancy Drug Safety")

from tensorflow.keras.models import load_model
model = load_model("Tuned_Artificial_Neural_Network_Smote_Drug_Safety_Model.h5")
tfidf_vectorizer = joblib.load("tfidf_vectorizer.pkl")
scaler = joblib.load("scaler.pkl")

onehot_encoder = joblib.load("fitted_onehot_encoder.pkl")
saved_feature_names = np.load("onehot_feature_names.npy", allow_pickle=True)

st.set_page_config(page_title="Pregnancy Drug Safety Predictor", layout="wide")
st.image("Pregnant_drug.png", width=150)
st.title("Pregnancy Drug Safety Predictor")
st.markdown("Enter drug details below to predict the pregnancy drug safety category. ")

# Text input
side_effects = st.text_area("Enter Side Effects", "")
# Categorical inputs
drug_class = st.selectbox("Drug Class", ["Select Drug Class"] + ['Miscellaneous antimalarials, Tetracyclines', 'Aldosterone receptor antagonists, Potassium-sparing diuretics', 'Tetracyclines',
       'Miscellaneous antineoplastics, Miscellaneous uncategorized agents', 'Topical acne agents, Vaginal anti-infectives', 'Topical acne agents', 'Sulfonamides',
       'First generation cephalosporins', 'Topical acne agents, Topical antipsoriatics', 'Unknown', 'Topical acne agents, Topical antibiotics', 'Contraceptives', 'Antacids, Laxatives',
       'Topical acne agents, Topical anti-rosacea agents', 'Topical acne agents, Topical keratolytics', 'Mouth and throat products', 'Topical antibiotics',
       'Contraceptives, Sex hormone combinations', 'Miscellaneous topical agents', 'Topical antipsoriatics','CNS stimulants', 'Adamantane antivirals, Dopaminergic antiparkinsonism agents',
       'Adrenergic uptake inhibitors for ADHD', 'Miscellaneous antidepressants, Smoking cessation agents', 'Antiadrenergic agents, centrally acting', 'Miscellaneous uncategorized agents',
       'Anorexiants, CNS stimulants', 'Nutraceutical products', 'Dopaminergic antiparkinsonism agents, Monoamine oxidase inhibitors', 'Serotonin-norepinephrine reuptake inhibitors',
       'Tricyclic antidepressants', 'Antiviral combinations', 'Antiviral boosters, Protease inhibitors', 'Integrase strand transfer inhibitor', 'Protease inhibitors',
       'Nucleoside reverse transcriptase inhibitors (NRTIs)', 'NNRTIs', 'Chemokine receptor antagonist', 'Miscellaneous antivirals', 'Antiviral boosters', 'Immune globulins',
       'Antihistamines, Miscellaneous anxiolytics, sedatives and hypnotics', 'Antihistamines','Miscellaneous anxiolytics, sedatives and hypnotics', 'Corticotropin',
       'Upper respiratory combinations', 'Cholinesterase inhibitors', 'Miscellaneous central nervous system agents', 'Antirheumatics, TNF alfa inhibitors', 'Vitamins',
       'Platelet aggregation inhibitors, Salicylates', 'Antianginal agents, Vasodilators', 'Antianginal agents', 'Cardioselective beta blockers', 'Calcium channel blocking agents',
       'Heparins', 'Non-cardioselective beta blockers', 'Antihyperlipidemic combinations, Miscellaneous antihypertensive combinations', 'Group II antiarrhythmics, Non-cardioselective beta blockers',
       'Calcium channel blocking agents, Group IV antiarrhythmics', 'Thrombin inhibitors', 'Glycoprotein platelet inhibitors', 'Benzodiazepines', 'Benzodiazepine anticonvulsants, Benzodiazepines',
       'Benzodiazepine anticonvulsants, Benzodiazepines, Miscellaneous antiemetics', 'Selective serotonin reuptake inhibitors', 'Gamma-aminobutyric acid analogs', 'Phenylpiperazine antidepressants',
       'Tetracyclic antidepressants', 'Triazine anticonvulsants', 'Opioids (narcotic analgesics)', 'Atypical antipsychotics', 'Miscellaneous anxiolytics, sedatives and hypnotics, Tricyclic antidepressants',
       'Psychotherapeutic combinations', 'Dibenzazepine anticonvulsants', 'Group I antiarrhythmics, Hydantoin anticonvulsants', 'Phenothiazine antiemetics, Phenothiazine antipsychotics',
       'Phenothiazine antipsychotics', 'Miscellaneous antidepressants', 'Leukotriene modifiers', 'Glucocorticoids', 'Interleukin inhibitors', 'Bronchodilator combinations', 'Anticholinergic bronchodilators',
       'Inhaled corticosteroids', 'Adrenergic bronchodilators', 'Antiasthmatic combinations', 'Carbonic anhydrase inhibitor anticonvulsants', 'Antimanic agents', 'Fatty acid derivative anticonvulsants',
       'Pyrrolidine anticonvulsants', 'Gamma-aminobutyric acid reuptake inhibitors', 'Expectorants', 'Macrolides', 'Aminopenicillins', 'Quinolones', 'Beta-lactamase inhibitors', 'Third generation cephalosporins',
       'Second generation cephalosporins', 'Penicillinase resistant penicillins', 'Carbapenems', 'Alkylating agents', 'Antimetabolites', 'Antibiotics / antineoplastics', 'Mitotic inhibitors',
       'Miscellaneous antineoplastics', 'Statins', 'Cholesterol absorption inhibitors', 'Fibric acid derivatives', 'Antihyperlipidemic combinations', 'Miscellaneous antihyperlipidemic agents, Vitamins',
       'Bile acid sequestrants', 'Selective immunosuppressants', 'Miscellaneous antihyperlipidemic agents', 'Topical rubefacient', 'Analgesic combinations', 'Laxatives', 'Minerals and electrolytes',
       'Anticholinergic antiemetics, Anticholinergic antiparkinson agents, Antihistamines, Miscellaneous anxiolytics, sedatives and hypnotics', 'Selective phosphodiesterase-4 inhibitors', 'Anthelmintics',
       'Antirheumatics, Interleukin inhibitors', 'Monoamine oxidase inhibitors', 'General anesthetics', 'Thyroid drugs', 'Insulin', 'Amylin analogs', 'Somatostatin and somatostatin analogs', 'Non-sulfonylureas',
       'SGLT-2 inhibitors', 'Incretin mimetics', 'Dipeptidyl peptidase 4 inhibitors', 'Sulfonylureas', 'Thiazolidinediones', 'Antidiabetic combinations', 'Meglitinides', 'Alpha-glucosidase inhibitors',
       'Dopaminergic antiparkinsonism agents, Prolactin inhibitors', 'Antidiarrheals', 'Antidiarrheals, Probiotics', 'Antitussives, Opioids (narcotic analgesics)', 'Miscellaneous antibiotics', 'Aminoglycosides',
       'Probiotics', 'Topical steroids', 'Antimetabolites, Antipsoriatics, Antirheumatics, Other immunosuppressants', 'Otic steroids', 'Antirheumatics, Other immunosuppressants', 'Calcineurin inhibitors',
       'Topical antihistamines', 'Topical steroids with anti-infectives', 'Topical anti-infectives', 'Topical emollients', 'Impotence agents', 'Agents for pulmonary hypertension, Impotence agents',
       'Impotence agents, Vasodilators', 'Peripheral opioid receptor antagonists', 'Topical anesthetics', 'Proton pump inhibitors', 'H2 antagonists', 'Miscellaneous GI agents', 'GI stimulants, Miscellaneous antiemetics',
       'Antacids', 'Antacids, Minerals and electrolytes', 'Miscellaneous genitourinary tract agents', 'Antacids, Phosphate binders', 'Anticholinergics / antispasmodics', 'Antigout agents, Antihyperuricemic agents',
       'Antihyperuricemic agents', 'Antigout agents', '5-aminosalicylates, Antirheumatics', 'Nasal steroids', 'Nasal antihistamines and decongestants', 'Nasal antihistamines and decongestants, Nasal steroids',
       'Antihistamines, Phenothiazine antiemetics', 'Allergenics', 'Purine nucleosides', 'Topical antivirals', 'Angiotensin Converting Enzyme Inhibitors', 'Angiotensin receptor blockers', 'Thiazide diuretics',
       'Loop diuretics', 'ACE inhibitors with thiazides', 'Vasodilators', 'Angiotensin II inhibitors with thiazides', 'Potassium sparing diuretics with thiazides', 'ACE inhibitors with calcium channel blocking agents',
       'Alpha-adrenoreceptor antagonists, Antiadrenergic agents, peripherally acting', 'Angiotensin II inhibitors with calcium channel blockers', 'Beta blockers with thiazides', 'Antiadrenergic agents, peripherally acting',
       'Miscellaneous antihypertensive combinations', 'Renin inhibitors', 'Cardioselective beta blockers, Group II antiarrhythmics', 'Antiadrenergic agents (central) with thiazides', 'Potassium-sparing diuretics',
       'Glucocorticoids, Inhaled corticosteroids', '5-aminosalicylates', 'Mast cell stabilizers', 'Urinary antispasmodics', 'Skeletal muscle relaxants', 'Anticholinergic antiemetics', 'Barbiturates',
       'Anticholinergic antiparkinson agents, Antihistamines, Miscellaneous anxiolytics, sedatives and hypnotics', 'Barbiturate anticonvulsants, Barbiturates', 'Sex hormone combinations', 'Antimigraine agents',
       'Nonsteroidal anti-inflammatory drugs', 'Cox-2 inhibitors', 'Uterotonic agents', 'Topical non-steroidal anti-inflammatories', 'Narcotic analgesic combinations', 'Nonsteroidal anti-inflammatory drugs, Salicylates',
       'Salicylates', 'Viscosupplementation agents', 'Bisphosphonates', 'Miscellaneous bone resorption inhibitors', 'Vitamin and mineral combinations', 'Parathyroid hormone and analogs',
       'Hormones / antineoplastics, Selective estrogen receptor modulators', 'Estrogens', 'Calcitonin', 'Miscellaneous analgesics', 'Skeletal muscle relaxant combinations', 'Local injectable anesthetics', 'Lincomycin derivatives',
       'Amebicides, Miscellaneous antibiotics', 'Glycopeptide antibiotics', 'Fourth generation cephalosporins', 'Oxazolidinone antibiotics', 'Aminoglycosides, Inhaled anti-infectives', 'Natural penicillins',
       'Next generation cephalosporins', 'Glycylcyclines', 'Cephalosporins / beta-lactamase inhibitors', 'Antipseudomonal penicillins', 'TNF alfa inhibitors', 'Antipsoriatics', 'Psoralens', 'Anorectal preparations',
       'Antimalarial quinolines, Antirheumatics', 'Antirheumatics, CD20 monoclonal antibodies', 'Antirheumatics, Selective immunosuppressants', 'Antirheumatics', 'CD52 monoclonal antibodies', 'Interferons', 'CD20 monoclonal antibodies',
       'Miscellaneous antipsychotic agents', 'Thioxanthenes', 'Benzodiazepine anticonvulsants', 'Miscellaneous anticonvulsants', 'Barbiturate anticonvulsants', 'Succinimide anticonvulsants', 'AMPA receptor antagonists', 'Progestins',
       'Platelet aggregation inhibitors', 'Thrombolytics', 'Neuraminidase inhibitors', 'Inhaled anti-infectives, Neuraminidase inhibitors', 'Urinary anti-infectives', 'Anorexiants', 'Peripherally acting antiobesity agents', 'Gonadotropins',
       'Anorexiants, CNS stimulants, Miscellaneous anticonvulsants'])
rx_otc = st.selectbox("Prescription or OTC", ["Select Rx/OTC", 'Rx', 'Rx/OTC', 'OTC'])
medical_condition = st.selectbox("Medical Condition", ["Select Condition"] + ['Acne', 'ADHD', 'AIDS/HIV', 'Allergies', "Alzheimer's", 'Angina', 'Anxiety', 'Asthma', 'Bipolar Disorder', 'Bronchitis', 'Cancer',
       'Cholesterol', 'Colds & Flu', 'Constipation', 'COPD', 'COVID 19', 'Depression', 'Diabetes (Type 1)', 'Diabetes (Type 2)', 'Diarrhea', 'Eczema', 'Erectile Dysfunction', 'Gastrointestinal',
       'GERD (Heartburn)', 'Gout', 'Hair Loss', 'Hayfever', 'Herpes', 'Hypertension', 'Hypothyroidism', 'IBD (Bowel)', 'Incontinence', 'Insomnia', 'Menopause', 'Migraine', 'Osteoarthritis',
       'Osteoporosis', 'Pain', 'Pneumonia', 'Psoriasis', 'Rheumatoid Arthritis', 'Schizophrenia', 'Seizures', 'Stroke', 'Swine Flu', 'UTI', 'Weight Loss'])
csa = st.selectbox("CSA Schedule",["Select CSA"] + ["Not Scheduled – Not FDA Categorized (N)","Schedule I – High abuse potential, no accepted medical use (M)",
        "Schedule II – High abuse potential, accepted medical use","Schedule III – Moderate/low physical dependence",
        "Schedule IV – Low abuse potential relative to III", "Schedule V – Lowest abuse potential"])
alcohol_interaction = st.selectbox("Alcohol Interaction", ["Select", "Yes", "No"])

if st.button("Predict Drug Category"):
    if (drug_class != "Select Drug Class" and rx_otc != "Select Rx/OTC" and medical_condition != "Select Condition" and
        csa != "Select CSA" and alcohol_interaction != "Select" and side_effects.strip() != ""):
        cat_input = pd.DataFrame([{'Drug_Classes': drug_class, 'Rx_Otc': rx_otc, 'Medical_Condition': medical_condition, 'Csa': csa,
                               'Alcohol_Interaction': alcohol_interaction }])
        tfidf_features = tfidf_vectorizer.transform([side_effects])
        encoded_cat = onehot_encoder.transform(cat_input)
        combined_features = hstack([tfidf_features, encoded_cat])
        combined_dense = combined_features.toarray()
        scaled_features = scaler.transform(combined_dense)
        csa_mapping = {"Not Scheduled – Not FDA Categorized (N)": "N", "Schedule I – High abuse potential, no accepted medical use (M)": "M",
                   "Schedule II – High abuse potential, accepted medical use": "2", "Schedule III – Moderate/low physical dependence": "3",
                   "Schedule IV – Low abuse potential relative to III": "4", "Schedule V – Lowest abuse potential": "5"}
        csa_value = csa_mapping[csa]
        label_map = {0: "A - Safest / No fetal risk", 1: "B - Safe / No human studies", 2: "C - Use with Caution / Animal risk, no human data",
                 3: "D - Risky / Evidence of human fetal risk", 4: "N - Unknown Category", 5: "X - Contraindicated / Known fetal harm" }
        probs = model.predict(scaled_features)
        pred_value = np.argmax(probs, axis=1)[0]
        category_label = label_map.get(pred_value, "Unknown")
        st.success(f"Predicted Pregnancy Category: **{category_label}**")
        st.write("Probabilities:", probs)
    else:
        st.warning("Please fill in all fields before predicting.")